project_id = "srartzeqcbxbytfixeiv"

[functions.admin-delete-user]
verify_jwt = false

[functions.audiencelab-api]
verify_jwt = true

[functions.create-stripe-products]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.reset-monthly-credits]
verify_jwt = false
