project_id = "srartzeqcbxbytfixeiv"

[functions.admin-delete-user]
verify_jwt = false

[functions.sync-reply-campaigns]
verify_jwt = false

[functions.audiencelab-api]
verify_jwt = false


[functions.stripe-webhook]
verify_jwt = false

[functions.reset-monthly-credits]
verify_jwt = false

[functions.validate-api-key]
verify_jwt = false

[functions.fetch-reply-teams]
verify_jwt = false

[functions.reply-webhook]
verify_jwt = false

[functions.setup-reply-webhook]
verify_jwt = false

[functions.fetch-integration-teams]
verify_jwt = false

[functions.fetch-available-campaigns]
verify_jwt = false

[functions.sync-reply-contacts]
verify_jwt = false

[functions.sync-reply-sequences]
verify_jwt = false

[functions.analyze-csv-knowledge]
verify_jwt = false

[functions.publish-resource]
verify_jwt = false

[functions.generate-copy]
verify_jwt = false

[functions.build-audience]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.check-and-use-credits]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.revamp-copy]
verify_jwt = false

[functions.send-heyreach-message]
verify_jwt = false

[functions.add-to-heyreach-campaign]
verify_jwt = false

[functions.get-agent-inbox]
verify_jwt = false

[functions.classify-reply]
verify_jwt = false

[functions.auto-sync-integrations]
verify_jwt = false

[functions.send-agent-reply]
verify_jwt = false

[functions.poll-reply-inbox]
verify_jwt = false

[functions.heyreach-webhook]
verify_jwt = false

[functions.sync-heyreach-campaigns]
verify_jwt = false

[functions.poll-heyreach-inbox]
verify_jwt = false

[functions.smartlead-webhook]
verify_jwt = false

[functions.sync-smartlead-campaigns]
verify_jwt = false

[functions.send-smartlead-email]
verify_jwt = false
